#!/usr/bin/env python3
"""
Lateral-view outlines of the mouse brain and hippocampus for the homepage anatomy intro.

Projects the Allen CCFv3 meshes already in public/assets/atlas (ccf.bin/ccf.json, see build-atlas.py)
onto the sagittal plane (antero-posterior × dorso-ventral), rasterises them and traces the outline.
The hippocampus outline is its projection seen through the cortex ("glass brain").

Usage:  python3 scripts/build-atlas-sagittal.py
Writes: src/data/atlas-sagittal.json   (SVG paths in CCF voxel units, 25 µm)
"""
import json
from pathlib import Path
import numpy as np
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
ATLAS = ROOT / 'public/assets/atlas'
K = 2  # raster pixels per voxel


def load():
    m = json.loads((ATLAS / 'ccf.json').read_text())
    buf = (ATLAS / m['binary']).read_bytes()
    out = {}
    for st in m['structures']:
        q = np.frombuffer(buf, dtype='<u2', count=st['positions'][1] * 3, offset=st['positions'][0]).reshape(-1, 3)
        v = q * m['scale'] + np.array(m['origin'])
        t = np.frombuffer(buf, dtype='<u2', count=st['indices'][1], offset=st['indices'][0]).reshape(-1, 3)
        out[st['id']] = (v, t)
    return out


def mask(meshes, w, h):
    im = Image.new('1', (w * K, h * K), 0)
    d = ImageDraw.Draw(im)
    for v, t in meshes:
        # mesh axes run opposite to CCF: AP = 528 − y, DV = 320 − z (checked against the coronal label sections)
        p = np.stack([528 - v[:, 1], 320 - v[:, 2]], 1) * K
        for tri in t:
            d.polygon([tuple(p[i]) for i in tri], fill=1)
    return np.array(im, dtype=bool)


def trace(m):
    """Outer boundary of the largest blob (Moore-neighbour tracing)."""
    m = np.pad(m, 1)
    ys, xs = np.nonzero(m)
    start = (ys[np.argmin(xs)], xs.min())
    nb = [(-1, 0), (-1, 1), (0, 1), (1, 1), (1, 0), (1, -1), (0, -1), (-1, -1)]
    pts, cur, back = [start], start, 6
    for _ in range(200000):
        for k in range(8):
            d = (back + 1 + k) % 8
            ny, nx = cur[0] + nb[d][0], cur[1] + nb[d][1]
            if m[ny, nx]:
                back = (d + 4) % 8
                cur = (ny, nx)
                break
        if cur == start:
            break
        pts.append(cur)
    return np.array([(x - 1, y - 1) for y, x in pts], dtype=float) / K


def smooth(p, n=3):
    for _ in range(n):
        p = (np.roll(p, 1, 0) + 2 * p + np.roll(p, -1, 0)) / 4
    return p


def rdp(p, eps):
    if len(p) < 3:
        return p
    a, b = p[0], p[-1]
    ab = b - a
    nrm = np.hypot(*ab) or 1
    q = p - a
    d = np.abs(ab[0] * q[:, 1] - ab[1] * q[:, 0]) / nrm
    i = int(np.argmax(d))
    if d[i] > eps:
        return np.vstack([rdp(p[: i + 1], eps)[:-1], rdp(p[i:], eps)])
    return np.array([a, b])


def path(p):
    p = rdp(smooth(p), 0.6)
    return 'M' + ' L'.join(f'{x:.1f} {y:.1f}' for x, y in p) + ' Z'


def main():
    ms = load()
    allv = ms[997][0]
    w, h = 532, 324
    brain = trace(mask([ms[997]], w, h))
    hip = trace(mask([ms[i] for i in ms if i != 997], w, h))
    x0, y0 = brain[:, 0].min(), brain[:, 1].min()
    x1, y1 = brain[:, 0].max(), brain[:, 1].max()
    secs = json.loads((ATLAS / 'sections/sections.json').read_text())['slices']
    out = {
        '_about': 'Generated by scripts/build-atlas-sagittal.py from the Allen CCFv3 meshes. Units: CCF voxels (25 µm); x = antero-posterior, y = dorso-ventral.',
        'viewBox': [round(x0 - 6, 1), round(y0 - 6, 1), round(x1 - x0 + 12, 1), round(y1 - y0 + 12, 1)],
        'brain': path(brain),
        'hippocampus': path(hip),
        'sections': [{'ap': s['ap_voxel'], 'bregma': s['bregma_mm_approx']} for s in secs],
    }
    (ROOT / 'src/data/atlas-sagittal.json').write_text(json.dumps(out, indent=1, ensure_ascii=False) + '\n')
    print(out['viewBox'], len(out['brain']), len(out['hippocampus']))


main()
